jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            helloworld2
            helloworld3
